#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you can
#       specify it by using SHELL=/bin/sh.custom (or similar) when running this
#       script.
#
#   (2) The Gradle wrapper cache is stored in the ~/.gradle directory, which should
#       be writable by the user executing this script.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while [[ -h "$PRG" ]]; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(cd "$(dirname "$PRG")" && pwd -P)/"$(basename "$link")"
    fi
done
APP_HOME=$( cd "$(dirname "$PRG")" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"

if [[ ! -f "$APP_HOME/gradle/wrapper/$APP_JAR" ]]; then
    echo "Error: $APP_JAR not found in $APP_HOME/gradle/wrapper/"
    exit 1
fi

# This is what's needed to make the wrapper work
if ! jar -tf "$APP_HOME/gradle/wrapper/$APP_JAR" > /dev/null 2>&1; then
    echo "Error: $APP_JAR is not a valid JAR file"
    exit 1
fi

set -o nounset
set -o errexit
trap 'echo "Error: Gradle wrapper script failed"' EXIT

# Determine the Java command to use to start the JVM.
if [[ -n "${JAVA_HOME:-}" ]] ; then
    if [[ -x "${JAVA_HOME}/jre/sh/java" ]] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="${JAVA_HOME}/jre/sh/java"
    else
        JAVACMD="${JAVA_HOME}/bin/java"
    fi
    if [[ ! -x "$JAVACMD" ]] ; then
        echo "Error: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || {
        echo ""
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    }
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" ; then
    MAX_FD_LIMIT=$(ulimit -H -n) 2>/dev/null || MAX_FD_LIMIT=65536
    ulimit -n $MAX_FD_LIMIT
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * the classpath
#   * -D...sysproperties setting
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, GRADLE_OPTS, and GRADLE_SCRIPT_ARGS
eval set -- $DEFAULT_JVM_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_NAME\"" -classpath "\"$APP_HOME/gradle/wrapper/$APP_JAR\"" org.gradle.wrapper.GradleWrapperMain "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ary =( $(xargs -n1 <<<  "$var") )
#   cmd="${ary[@]}"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be interpreted by sh, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $GRADLE_OPTS "\-Dorg.gradle.appname=$APP_NAME"" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
