= Reqstool Demo

This project acts as a demo on how to integrate Reqstool into your project. In this simple project, you are able to see how Reqstool can be used and how the different files relate to each other.

In this demo, we are showcasing how we define requirements and tests for a microservice, and also imports and implements requirements from an external system (ext-001).

== Prerequisites

* Java 21
* Maven or Gradle
* Python 3.10
* Reqstool >= 0.5.7 (`pipx install reqstool`)

== Usage

Before you can analyze the codebase with Reqstool, the project has to be built in order to generate the required annotation classes which will reside under the target folder of this project.

=== Maven

From the root of your project, run:

[source,bash]
----
mvn clean install
----

=== Gradle

From the root of your project, run:

[source,bash]
----
gradle build
----

=== Check Status

When the project is built and the tests are run (one of them is expected to fail), you can check the status of the project by running:

[source,bash]
----
reqstool status local -p {root_of_project}/docs/reqstool
----

=== Generate Reports

If you would like to generate your requirement data as an AsciiDoc report file:

[source,bash]
----
reqstool report-asciidoc local -p {root_of_project}/docs/reqstool -o {path-to-file}filename.adoc
----

If you would like to generate your requirement data as a JSON file:

[source,bash]
----
reqstool export local -p {root_of_project}/docs/reqstool -o {path-to-file}filename.json
----

== License

MIT License.
