# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json

metadata:
  urn: demo
  variant: microservice
  title: Some Microservice Requirement Title
  url: https://url.example.com

# Import all requirements from local external system 001
imports:
  local:
    - path: ./ext-001

requirements:
  - id: REQ_010
    title: Title REQ_010
    significance: may
    description: Description REQ_010
    rationale: Rationale REQ_010
    categories: ["functional-suitability", "maintainability"]
    revision: 0.0.1
  - id: REQ_020
    title: Title REQ_020
    significance: may
    description: Description REQ_020
    rationale: Rationale REQ_020
    categories: ["functional-suitability", "maintainability"]
    revision: 0.0.1
