on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - run: mvn clean verify
      - name: Run reqstool status command
        run: |
          pip install reqstool
          reqstool status local -p "$GITHUB_WORKSPACE"/docs/reqstool
